version: '3.8'

services:
  triton-mount:
    image: nvcr.io/nvidia/tritonserver:23.10-py3
    volumes:
      - ./models:/models
    command: tritonserver --model-repository=/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  streamlit-app:
    build:
      context: .
      dockerfile: docker/streamlit.Dockerfile
    ports:
      - "8501:8501"
    environment:
      - APP_TRITON_URL=triton-mount:8001
      - APP_USE_HTTP=false
      - APP_PUSHGATEWAY_URL=pushgateway:9091

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./docker/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources